kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      default: main
      type: string
    - name: app-name
      type: string
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        kind: Task
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: clone
      runAfter:
        - cleanup
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: output
    - name: lint
      runAfter:
        - clone
      taskRef:
        kind: Task
        name: flake8
      params:
        - name: image
          value: python:3.9-slim
        - name: args
          value: service
      workspaces:
        - name: source
          workspace: output
    - name: tests
      runAfter:
        - clone
      taskRef:
        kind: Task
        name: nose
      params:
        - name: args
          value: "-v --with-spec --spec-color --with-coverage --cover-package=app"
      workspaces:
        - name: source
          workspace: output
    - name: build
      runAfter:
        - lint
        - tests
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output
    - name: deploy
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: "oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -"
  workspaces:
    - name: output
